# Generated by go2rpm 1.14.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/subpop/go-log
%global goipath         github.com/subpop/go-log
Version:                0.1.2

%gometa -L -f

%global common_description %{expand:
Package log implements a simple level logging package that maintains API
compatibility with the standard library log package. It extends the standard
library log.Logger type with a Level type that can be used to define output
verbosity. It adds additional methods that will be printed only if the logger
is configured at or below a given level.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           golang-github-subpop-log
Release:        %autorelease
Summary:        Simple level log package

License:        GPL-3.0-only
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
